In [1]:
# Numpy 

In [3]:
# 1D array 
import numpy as np
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [5]:
# 2d array 
b = np.array([[1,2,3],[4,5,6]])
b = np.array([[2,4,6],[3,7,0]])
b

array([[2, 4, 6],
       [3, 7, 0]])

In [6]:
# 3d array 
c  = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [9]:
# change data types 
a = np.array([1,2,3],dtype=float)
b = np.array([4,5,6],dtype=complex)

a
b

array([4.+0.j, 5.+0.j, 6.+0.j])

In [11]:
b = np.arange(1,10)
x = np.arange(2,5)
b
x

array([2, 3, 4])

In [21]:
x = np.arange(1,20,4)
x

array([ 1,  5,  9, 13, 17])

In [18]:
# reshape
x = np.arange(1,11).reshape(5,2)
y = np.arange(1,11).reshape(5,2)
x
y

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [20]:
# for initialize purposed 

# np.ones & np.zeros 
y = np.ones((3,2)) 
y = np.ones((2,2)) 
y

z = np.zeros((3,2))
z = np.zeros((2,2))
z

y,z

(array([[1., 1.],
        [1., 1.]]),
 array([[0., 0.],
        [0., 0.]]))

In [26]:
# random 
import numpy as np
x = np.random.random((2,4))
x = np.random.random((2,4))
x

array([[0.16620563, 0.58651654, 0.91771827, 0.19948999],
       [0.26583028, 0.30439569, 0.29531467, 0.78165276]])

In [42]:
# linspace -> equally distribute 

a = np.linspace(1,10,20)
a

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [27]:
# identity 
s = np.identity(3)
s = np.identity(4)
s

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
# numpy attributes 
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a1,a2,a3

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]),
 array([[[0, 1],
         [2, 3]],
 
        [[4, 5],
         [6, 7]]]))

In [31]:
# ndim 
a1.ndim,a2.ndim,a3.ndim
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [32]:
# shape 
a1.shape 
a2.shape
a3.shape

a1.shape, a2.shape, a3.shape

((10,), (3, 4), (2, 2, 2))

In [63]:
# size
a1.size
a1

a2.size
a2

a3.size 
print(a3.size) 

8


In [35]:
# item size 
a1.itemsize
a1

a2.itemsize
a2

a3.itemsize
a3

print(a1, a2, a3)

[0 1 2 3 4 5 6 7 8 9] [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]] [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [94]:
# dtype 
s1 = np.array(10,dtype = np.int64)
s2 = np.array(12,dtype=np.int32)
s3 = np.arange(8).reshape(2,2,2)
print(s1.dtype) 
print(s2.dtype)
print(s3.dtype)

int64
int32
int32


In [116]:
# change data types 
# astype 

x1 = np.arange(1,10)
x1.astype(np.int64)
# x1.dtype

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [121]:
# Array Operations 
# scalar and vector 
b1 = np.arange(12).reshape(3,4)
b2 = np.arange(12,24).reshape(3,4)
b1, b2

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]))

In [129]:
# scalar -> Arithmetic 
b1 * 2
b1 - 2
b1 / 4
b1 % 3


array([[0, 1, 2, 0],
       [1, 2, 0, 1],
       [2, 0, 1, 2]], dtype=int32)

In [134]:
# scalar -> relational 
b1 > 5
b1 >= 3
b2 == 3
b2 <6

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [145]:
# vecror -> arithmetic 
x = np.arange(12).reshape(3,4)
y = np.arange(12,24).reshape(3,4)

x+y
x-y
x ** y

array([[          0,           1,       16384,    14348907],
       [          0, -1564725563,  1159987200,   442181591],
       [          0,  1914644777, -1304428544,  -122979837]])

In [152]:
# Array Functions 
q = np.random.random((3,3))
q = np.round(q * 100)
q

array([[58., 97., 36.],
       [11., 26.,  6.],
       [53., 87., 85.]])

In [159]:
# max/min/sum/pro 
q.max()
q.min()
q.sum()
q.prod()

# or 

np.max(q)
np.min(q)
np.sum(q)
np.prod(q)

136217705326560.0

In [163]:
# 0 ->col and 1->rows
q.max(axis = 0) 
q.min(axis=1)



array([36.,  6., 53.])

In [183]:
# mean / median / mode / var
q.mean(axis = 1)
np.median(q, axis = 1)
np.std(q)
np.var(q)

1010.6666666666666

In [188]:
# trignometric function 
np.sin(q)

array([[ 0.99287265,  0.37960774, -0.99177885],
       [-0.99999021,  0.76255845, -0.2794155 ],
       [ 0.39592515, -0.82181784, -0.17607562]])

In [193]:
# dor product 
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(4,3)
np.dot(a1,a2)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [197]:
# log and exp 
np.log(a1)
np.exp(a2)

C:\Users\hafiz\AppData\Local\Temp\ipykernel_8304\3534733668.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(a1)


array([[1.62754791e+05, 4.42413392e+05, 1.20260428e+06],
       [3.26901737e+06, 8.88611052e+06, 2.41549528e+07],
       [6.56599691e+07, 1.78482301e+08, 4.85165195e+08],
       [1.31881573e+09, 3.58491285e+09, 9.74480345e+09]])

In [202]:
# round/floor/cell 
np.round(np.random.random((2,3))*100)
np.floor(np.random.random((2,3))*100)
np.ceil(np.random.random((2,3))*100)




array([[89., 26., 78.],
       [43.,  9., 36.]])

In [206]:
# indexing and slicing 
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a1
a2
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [48]:

print(a1)
print(a1[3]) #for one dimension 
a1[1:9:3]


[0 1 2 3 4 5 6 7 8 9]
3


array([1, 4, 7])

In [49]:
# for 2 dimension 
print(a2)
a2[2,2]

a2.astype(np.int32)[0,3]
a2.astype(np.int32)[1,1]

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


5

In [42]:
print(a3)
a3[1,1,1]
a3[0,1,0]
a3[0,1,0]
a3[0,0,1]

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


1

In [43]:
# slicing provides more items 
# for one dimension 
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [236]:
a1[1:4]
a1[1:7:3]

array([1, 4])

In [239]:
# for 2 dimension 
a2


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [52]:
a2[:,1]
a2[:,2]
a2[:2,:2]

array([[0., 1.],
       [4., 5.]])

In [243]:
# indexing and slicing 
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [280]:
# for one dimension 
print(a1)
a1[3]
a1[1:4]

[0 1 2 3 4 5 6 7 8 9]


array([1, 2, 3])

In [53]:
print(a2)
a2[1,2]
a2[2,1]

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


9.0

In [254]:
print(a2)
a2[2,3]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


11

In [257]:
print(a2)
a2[1,3]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


7

In [262]:
print(a3)
a3[1,1,0]

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


6

In [263]:
print(a3)
a3[0,0,0]

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


0

In [267]:
# slicing 
a1
a1[2:6:2]

array([2, 4])

In [272]:
print(a2)
a2[0,:]
a2[1,:]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([4, 5, 6, 7])

In [282]:
print(a2)
a2[:,0]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([0, 4, 8])

In [288]:
print(a2)
print(a2[:,3])
print(a2[1,:])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 3  7 11]
[4 5 6 7]


In [291]:
print(a2)
a2[1:,1:3]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 5,  6],
       [ 9, 10]])

In [298]:
print(a2)
a2[0:2,2:4]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[2, 3],
       [6, 7]])

In [301]:
print(a2)
a2[0:2,0:2]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[0, 1],
       [4, 5]])

In [55]:
# for alternate 
print(a2)
a2[0:2:2,:3:3]

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


array([[0.]])

In [59]:
print(a2)
a2[1:2,2:3]

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


array([[6.]])

In [66]:
a4 = np.arange(27).reshape(3,3,3)
print(a4)

a4[0,1,1]
a4[1,:,2]



[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


array([11, 14, 17])

In [75]:
a4
a4[2,1:3,1:3] #slicing 
a4[1,1,1]  #indexing

13

In [79]:
print(a4)
a4[::2,0,::2]

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


array([[ 0,  2],
       [18, 20]])

In [87]:
a4
a4[0:2,1,0:2]

array([[ 3,  4],
       [12, 13]])

In [91]:
# iterating over array 
a1
for i in a1:
    print(i)


0
1
2
3
4
5
6
7
8
9


In [95]:
a2
for i in a2:
    print(i)

[0. 1. 2. 3.]
[4. 5. 6. 7.]
[ 8.  9. 10. 11.]


In [98]:
a3
for i in a3:
    print(i)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [102]:
# npiter convert into 1d array and find easily specific value 
a3

for i in np.nditer(a3):
    print(i)


0
1
2
3
4
5
6
7


In [103]:
# reshaping 

# 1. reshape
# 2. transpose
# 3. ravel

In [107]:
# transpose 
np.transpose(a2)
a2.T

array([[ 0.,  4.,  8.],
       [ 1.,  5.,  9.],
       [ 2.,  6., 10.],
       [ 3.,  7., 11.]])

In [110]:
# ravel convert into 1 d array 
a3
a3.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [129]:
# stacking 
# horizontal stacking 

x1 = np.arange(12).reshape(3,4)
x2 = np.arange(12,24).reshape(3,4)
x3 = np.arange(2)
print(x1, x2, x3)

np.hstack((x1,x2))
np.vstack((x1,x2))




[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] [0 1]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [138]:
# splitting 
# horizontal splitting 
# vertical splitting 

x4 = np.arange(12).reshape(3,4)
x4

np.hsplit(x4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [141]:
x6 = np.arange(12)
x6
np.hsplit(x6,4)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]

In [151]:
# vsplit 
x7 = np.arange(12).reshape(3,4)
x7

np.split(x7,2)

ValueError: array split does not result in an equal division