In [ ]:
# sorted 

In [2]:
import numpy as np

a = np.random.randint(1,100,15)
a

array([64, 58, 97, 29, 17, 60, 29, 28, 26, 98, 95, 69, 70, 11, 55])

In [5]:
b = np.random.randint(1,100,24).reshape(4,6)
b



array([[57,  5, 17,  9, 74, 84],
       [52, 93, 17, 63, 78, 97],
       [45, 60,  2, 72, 15, 20],
       [82, 86, 95, 55, 74, 67]])

In [8]:
print(np.sort(a))
print(np.sort(b))

# rows wise ascending 

[11 17 26 28 29 29 55 58 60 64 69 70 95 97 98]
[[ 5  9 17 57 74 84]
 [17 52 63 78 93 97]
 [ 2 15 20 45 60 72]
 [55 67 74 82 86 95]]


In [10]:
np.sort(b, axis = 0)

# coloumn wise sorting 

array([[45,  5,  2,  9, 15, 20],
       [52, 60, 17, 55, 74, 67],
       [57, 86, 17, 63, 74, 84],
       [82, 93, 95, 72, 78, 97]])

In [16]:
np.append(a,100)
a

array([64, 58, 97, 29, 17, 60, 29, 28, 26, 98, 95, 69, 70, 11, 55])

In [17]:
# concatenate 
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)
np.concatenate((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [19]:
x = np.array([1,1,1,2,3,4,4,4])
np.unique(x)

array([1, 2, 3, 4])

In [23]:
# expand dim 
a = np.arange(6).reshape(2,3)
np.expand_dims(a, axis = 0)

array([[[0, 1, 2],
        [3, 4, 5]]])

In [27]:
# where provides the indices of non-zero elements
a = np.array([1,2,0,0,4,0])
np.where(a!=0)
np.where(a < 2)

(array([0, 2, 3, 5], dtype=int64),)

In [32]:
# replace all values with 0 grater than 50 
a = np.array([1,2,3,4,65,76,86])
np.where(a>50,0,a)

array([1, 2, 3, 4, 0, 0, 0])

In [35]:
# argmax provides max number index 
a = np.array([1,2,3,4,65,76,86])
np.argmax(a)
np.argmin(a)

0

In [45]:
# cumsum  cummulative sum 
a = np.array([[1,2,3,4,65,76,86]])
np.cumsum(a)
a.shape 
a.size 

7

In [47]:
# cumprod 
np.cumprod(a)

array([       1,        2,        6,       24,     1560,   118560,
       10196160])

In [57]:
# percentile kitne percent log apse piche hai 
a
np.percentile(a,0)
np.percentile(a,50)
# np.median(a)
# np.percentile(a,100)


4.0

In [62]:
a = np.arange(9)
a
np.histogram(a, bins = [0,10,20,30,40])

(array([9, 0, 0, 0], dtype=int64), array([ 0, 10, 20, 30, 40]))

In [64]:
# co relation  
salary = np.array([20000,30000,40000])
experience = np.array([1,2,3])
np.corrcoef(salary,experience)

array([[1., 1.],
       [1., 1.]])

In [67]:
# isin is multiple items serach in the array 
a = np.arange(9)
a

items = [1,2,3]
np.isin(a,items)

array([False,  True,  True,  True, False, False, False, False, False])

In [70]:
# flip ascending to descending order 
a = np.arange(9)
a
np.flip(a)

array([8, 7, 6, 5, 4, 3, 2, 1, 0])

In [74]:
# np.put changes perminantly 
a = np.array([1,2,3,4,5])
np.put(a,[0,1],[100,200])
a

array([100, 200,   3,   4,   5])

In [76]:
# set function 
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [78]:
np.intersect1d(m,n)

array([3, 4, 5])

In [84]:
print(np.setdiff1d(n,m))
print(np.setdiff1d(m,n))


[6 7]
[1 2]


In [86]:
# is mai difference btayega 

np.setxor1d(m,n)

array([1, 2, 6, 7])

In [91]:
# min and maximum  values 
np.clip(m,m_min=1,m_max=5)

TypeError: clip() missing 2 required positional arguments: 'a_min' and 'a_max'