In [2]:
# speed comparison  between list vs numpy 

import numpy as np
import time 

l1 = [i for i in range (10000000)]
l2 = [i for i in range (100000000000)]

l3 = []

start = time.time()
l3.append(l1+l2)
print(start - time.time())

# start = time.time()
# l3 = [x+y for x,y in zip(l1,l2)]
# print(time.time() - start)

# start = time.time()
# l4 = np.array(l1) + np.array(l2)
# print(time.time() - start)

In [ ]:
# memory 

import sys

l1 = [1,2,3,4,5,6,7,8,9,10]
l2 = [1,2,3,4,5,6,7,8,9,10]

print(sys.getsizeof(l1))
print(sys.getsizeof(l2))

136
136


In [ ]:
# how tto reduce memory size 
import numpy as np 
import sys
a = np.arange(10000,dtype=np.int32)
b = np.arange(10000,dtype=np.int8)
print(sys.getsizeof(a))
print(sys.getsizeof(b))
print(a)
print(b)

40112
10112
[   0    1    2 ... 9997 9998 9999]
[ 0  1  2 ... 13 14 15]


In [ ]:
# advance indexing and slicing 


<!-- normal  indexing and slicing 
 -->

In [ ]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a[1,1]

5

In [ ]:
a[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
# fency indexing (when we not find the value through normal indexing)
# when we find 1st, 2nd and 3rd row 
print(a)
a[[0,1,1]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [4, 5, 6, 7]])

In [ ]:
b = np.arange(24).reshape(6,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# find unpattern rows 
b
b[[0,2,3,5]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [ ]:
# find unpattern columns 
b
b[:,[0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [ ]:
# boolean indexing 
x = np.random.randint(1,100,24).reshape(6,4)
x

array([[34, 95, 13, 73],
       [32, 35, 92, 73],
       [35, 24,  5, 30],
       [20, 43, 40, 97],
       [63,  5, 82, 75],
       [28, 67,  7, 45]])

In [ ]:
# find all numbers grater than 50 
x[x>50]
 

array([95, 73, 92, 73, 97, 63, 82, 75, 67])

In [ ]:
# find out even number 
x [x%2 == 0]

array([34, 32, 92, 24, 30, 20, 40, 82, 28])

In [ ]:
# find out grater thn 50 and are even number 
x[(x>50) & (x%2==0)]

array([92, 82])

In [ ]:
# find all numbers which not divisible by 7 
x[~(x % 7 == 0)]

array([34, 95, 13, 73, 32, 92, 73, 24,  5, 30, 20, 43, 40, 97,  5, 82, 75,
       67, 45])

In [ ]:
# Broadcasting 
# how numpy treats the array
# smaller type of array 



In [5]:
# same shape 
import numpy as np
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)
print(a)
print(b)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [1]:
import numpy as np
a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)
print(a)
print(b)       

print(a + b)

[[0 1 2]
 [3 4 5]]
[[0 1 2]]
[[0 2 4]
 [3 5 7]]


In [3]:
# working with mathematical formula 
a = np.arange(12)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021])

In [5]:
# working with missing values 
a = np.array([1,2,3,np.nan,5,6])
a

array([ 1.,  2.,  3., nan,  5.,  6.])

In [7]:
np.isnan(a)

array([False, False, False,  True, False, False])

In [10]:
a[np.isnan(a)]

array([nan])

In [13]:
a[~np.isnan(a)]

array([1., 2., 3., 5., 6.])